name: cache-update

on:
  schedule:
    - cron: '0 0 */3 * *' # every 30m for testing

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:    # Cache location for arm tools
    - name: Cache arm-none-eabi-gcc tools
      id: cache-arm-gcc
      uses: actions/cache@v1
      with:
        path: $HOME/arm-none-eabi-gcc-9-2019-q4
        key: ${{ runner.os }}-arm-gcc-9-2019-q4

    # Get the arm-non-eabi-gcc toolchain   
    - name: Install arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1
      with:
          release: '9-2019-q4' # The arm-none-eabi-gcc release to use.
          directory: $HOME/arm-none-eabi-gcc-9-2019-q4
